### PR TITLE
zokou vf

### PR DESCRIPTION
**Pull request by babacarndia**
IMG-20241230-WA0016
Zokou-MD-WHATSAPP-BOT;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUJ5aWd1ZXpORW5pNm1sYUphTmxPbkRwajJ4SHpJTHRCQjlDQ05WQXgxcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMHlwUUszR2ZTRUtmajdYSENQQ3hrUVpoM25FR0V5dzcwUWtRVXMwcTlHOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwQkszc0dvdG83djAxNVowZnB1a1JNNHREdGREaWtuYkpOVjJDVmFkb0ZjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJOMFEwMHk5UVVSTktvWXlOaTlSNW5wTW1IV0YxTXBaeEg3bWxrRDBiVkdnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFFWndtd3ZaWGZOU1BEazhSQVZNZnVqaVZjUFJHUjBteDZTZldtMjA4bG89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVIS0RrUDkwWFlOSXZ6cGF4UGxkWGFYT3MvN281ZUN0a1dValkvSWFLMW89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0FqK3c2SlY3YS9sQ09scldqK3RjMmdwdlpXcERFV2hIYk5HSHJYbkVIdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTzcrZndDV3ovT3Jubi9pN3ZiZkRkL2FyUnhJcnBKU1RwVTltZlFoeDZrND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVIcS9MU1I3K1FJT1hvaWRXOWJCbytoTk1RYmM4T1pXWTNkR25xQ3grdXo2eG84dTd3Z3JjNlpCaVlkYkNObzFEYXFXMHZka1hPQkt3dks5V3Y0SmdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjA2LCJhZHZTZWNyZXRLZXkiOiJrSnJObHpsVWl6T0tkdnZZZXRzNjBBNUNGSlhYUFpoN3pVU3NKVU8vVjVjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI5QTdENU1QRiIsImxhc3RQcm9wSGFzaCI6IjNBb1NocyIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSUVnPT0ifSwibWUiOnsiaWQiOiIyMjE3NzcwNjMzNDI6NDNAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoifijigbbigbbwnZq78J2Qg/CdkIvigbcpfiDwnZCD8J2QhiDwnZqp8J2aqvCdkJTwnZq08J2aryIsImxpZCI6IjIxMDkzNDg3MDEwNjM0NDo0M0BsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0orNHpZRUNFSVNHekxzR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IndHdkdtWVB4TVp1QkQ2b1lWakdabUxJM3B3ZXdVN2wxaTZwb09ZeisvVDQ9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImZXcTRsUkNKdVRVSUZjZFgxclMzTW5FUmY5ZUY4MVg1OW94aHAyQXR6emFUaklDZUFrbWxzK0t0WlFaTEl5MlBqSjNXc05qZnZVblZKRDI1ei9saERRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJoQy9rWFZ4eU1WSWV6bmtxQVJoWjkwNkNYaVltMlZ4U3JJWk80dXBGU0NuYU9nQ0I3Ulpwa3lYRkpGMzE1WVpZcWxndGo1SjZFYkszU0FUZWQ3b1Zodz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIyMTc3NzA2MzM0Mjo0M0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJjQnJ4cG1EOFRHYmdRK3FHRll4bVppeU42Y0hzRk81ZFl1cWFEbU0vdjArIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM1NTkwNjYzLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUlsOCJ9

### CODE REVIEW

**Comment by babacarndia** [comment]
ajoutez votre commentaire ici

**Comment by babacarndia** [comment]
Très facile

**Comment by babacarndia** [comment]
IMG-20241230-WA0016

**Review by abdiasspy — COMMENTED** [review]
Zokou-MD-WHATSAPP-BOT;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY1BXRXFxeXpOVjZVRWdLS05kUlBmcDFzeVNJYkJ1M2UyUzg1OXRDWHNrMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0Q1SnUzRW5OQlE3cHE1RHJ1eS9DK1IyOXZsbVpLSEgyenZLMVN0YVdpND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJxT2Q5aG4zaFVsdVhub1UxaHhjRTZGT2U1bDNWZnEzM2YxSWtKMGpqblhZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIvNi9ESFNjMUVCUUkxcEtEdXg0dENsRS9BWHgwdm5USllQSWRTbDFvL0hjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZPMDdCVmxxdjI1WGR0ZHFIclcwa2VpbWtLeFRUWnVQT1dES2ovMWJURUU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Img5WmxkdzBOVGoxY2tGUGxzUVdwb0w2aUtIRHhHNkxjVnA3UWc5LzZNeDg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE1IM1Z2VitVc0NHRWNhMERwdU1rd09hbUF3RnBwKzYrNjNrOUJQZlgxUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaVZYU0EzU1VnblFuYXNtNW9WdjRMazlSaEwrOWJSVWpmOGREZ0FNQjR4TT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkR6czhTUjU2UU91UjFIanhJeERuOWNEcnNZaVg5NE1HRHR3WXdUd1NFa2lWbDN6L0hvZ0JEM1RzcmpWSHlHZHk3Z2U4YjdGK1pyUytPQk9XZUl3L0R3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTY0LCJhZHZTZWNyZXRLZXkiOiJrb2xGclhVUlpRaDhNa1lDKzZQZGlzUDBUbGFvODNoU3hRbHA3c1laZ0tRPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIyNTA3MTUzNzA2MzhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODYxODJBQUNFRDNDRTY5ODc3ODkxQjE1RjJGNjkxRkUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNjM2MjkyOH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiSldQOUM0TkYiLCJsYXN0UHJvcEhhc2giOiIzeFhXWVoiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlBZz09In0sIm1lIjp7ImlkIjoiMjI1MDcxNTM3MDYzODozQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Imwg6pmw8J2Rs/CdkpbwnZKH8J2Sh/Cdkpooy4pvzLbMtsy34bSXb8y2zLbMtylfbCDqmbDwnZG68J2SkfCdkoBsIOqZsCIsImxpZCI6IjI1NjAxOTI0MjQxODMyMjozQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTktqd1BBRUVLT1grN3NHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQktqa01Ocm5hTERrQ1Z0azhSdytvQStIK2I1WVZIcDdJVC9tK3M0VkpTMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiUkUyeG5tOXdMenQwdU03V2YxdFhrZ1FwcE5DQ0k1SVdzSitvK0Q5YWJRWEtkWmxRNDBDRGNFWnZjQzR2aEtvTWJ6ZHo2aWtqQW5YbkVpQXBIS0VHQkE9PSIsImRldmljZVNpZ25hdHVyZSI6IkF2anVJYzF6SmJOSnord0RzVURLNGRmRk80TGpZMVdHYTllNU9zVDVFOU9EckVpd0FwZWRqZElFQ1Y0OTZ5SFFwcGJOL055b1FKNFhLcGNZWkRiaUFBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjI1MDcxNTM3MDYzODozQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlFTbzVERGE1Mml3NUFsYlpQRWNQcUFQaC9tK1dGUjZleUUvNXZyT0ZTVXQifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzYzNjI5MTksIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRHdsIn0=

**Pull request closed without merging**
